version: "3.3"
services:

  etcd:
    image: bitnami/etcd
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - etcd_net
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379

networks:
  etcd_net:
    driver: bridge
