version: "3.3"
services:

  e3w:
    image: soyking/e3w
    volumes:
      - ./etc/config.default.ini:/app/conf/config.default.ini
    ports:
      - "8080:8080"
    networks:
      - etcd_net
    depends_on:
      - etcd

networks:
  etcd_net:
    driver: bridge

  etcd_external:
    driver: overlay
